# conda env create --file environment.yml
# conda env update --file environment.yml
name: gtex-bases
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biomart
  - bioconductor-genomicranges
  - bioconductor-gviz
  - bioconductor-rsubread
  - bioconductor-rtracklayer
  - r-data.table
  - r-base=3.6
  - r-stringr
  - samtools
  - subread
