# conda env create --file environment.yml
# conda env update --file environment.yml
name: gtex-bases
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biomart
  - bioconductor-genomicranges
  - bioconductor-gviz
  - bioconductor-rsubread=1.28.1
  - bioconductor-rtracklayer
  - r-data.table
  - r-base=3
  - r-stringr
  - samtools
  - sra-tools
  - subread=1.6.4
